plugins {
    id 'java-library'
    id 'idea'
    id 'net.neoforged.moddev' version '1.0.14'
}

version = "${minecraft_version}-${mod_version}"
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
    maven {
        url = 'https://www.cursemaven.com'
        content { includeGroup 'curse.maven' }
    }
    maven {
        url = 'https://maven.theillusivec4.top/'
        content { includeGroup 'top.theillusivec4.curios' }
    }
    maven {
        url = 'https://maven.blamejared.com/'
        content { includeGroup 'mezz.jei' }
    }
}

neoForge {
    version = neo_version
    accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

    parchment {
        minecraftVersion = parchment_minecraft_version
        mappingsVersion = parchment_mappings_version
    }

    runs {
        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }
    }

    mods {
        backpackininventory { sourceSet sourceSets.main }
    }

    unitTest {
        enable()
        testedMod = mods.backpackininventory
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation('curse.maven:sophisticated-core-618298:8705083') { transitive = false }
    implementation('curse.maven:sophisticated-backpacks-422301:8687841') { transitive = false }
    compileOnly('curse.maven:trashslot-235577:8163135') { transitive = false }
    compileOnly 'top.theillusivec4.curios:curios-neoforge:9.5.1+1.21.1'
    compileOnly 'mezz.jei:jei-1.21.1-neoforge:19.44.0.403'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.11.4'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.4'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.named('jar') {
    manifest {
        attributes 'Implementation-Title': mod_name,
                'Implementation-Version': project.version,
                'Implementation-Vendor': 'Sean'
    }
}
