modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config="backpackininventory.mixins.json"

[[mods]]
modId="backpackininventory"
version="${file.jarVersion}"
displayName="Backpack in Inventory"
authors="Sean"
description='''Adds a combined player inventory and Sophisticated Backpack screen.'''

[[dependencies.backpackininventory]]
modId="neoforge"
type="required"
versionRange="[21.1.243,22)"
ordering="NONE"
side="BOTH"

[[dependencies.backpackininventory]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.backpackininventory]]
modId="sophisticatedbackpacks"
type="required"
versionRange="[3.25.78,3.26)"
ordering="AFTER"
side="BOTH"

[[dependencies.backpackininventory]]
modId="sophisticatedcore"
type="required"
versionRange="[1.4.90,1.5)"
ordering="AFTER"
side="BOTH"

[[dependencies.backpackininventory]]
modId="curios"
type="optional"
versionRange="[9.5.1,10)"
ordering="AFTER"
side="BOTH"

[[dependencies.backpackininventory]]
modId="jei"
type="optional"
versionRange="[19.44,20)"
ordering="AFTER"
side="CLIENT"

[[dependencies.backpackininventory]]
modId="trashslot"
type="optional"
versionRange="[21.1.11,22)"
ordering="AFTER"
side="CLIENT"

[[dependencies.backpackininventory]]
modId="sophisticatedstorage"
type="optional"
versionRange="[1.5.91,1.6)"
ordering="AFTER"
side="BOTH"
